# Generated by Django 4.2.11 on 2024-05-09 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_media"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="reaction",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="reaction",
            name="media",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="main.media",
            ),
        ),
        migrations.AlterField(
            model_name="reaction",
            name="post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="main.post",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="reaction",
            unique_together={("user", "media", "post", "reaction_type")},
        ),
    ]
